version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run:
          type: shell
          name: install dependencies
          command: |
            sudo apt-get install libxml2-utils maven
            sudo ln -s /usr/bin/python3 /usr/bin/python
      - run:
          type: shell
          name: install bats-core
          command: |
            git clone https://github.com/bats-core/bats-core.git
            cd bats-core
            ./install.sh $HOME
      - run:
          name: Run jboss-kie-common bats tests
          command: |
            $HOME/bin/bats jboss-kie-common/tests/bats/
      - run:
          name: Run jboss-kie-kieserver bats tests
          command: |
            $HOME/bin/bats jboss-kie-kieserver/tests/bats/
      - run:
          name: Run jboss-kie-smartrouter bats tests
          command: |
            $HOME/bin/bats jboss-kie-smartrouter/tests/bats/
      - run:
          name: Run jboss-kie-wildfly-common bats tests
          command: |
            $HOME/bin/bats jboss-kie-wildfly-common/tests/bats/
      - run:
          name: Run jboss-kie-workbench bats tests
          command: |
            $HOME/bin/bats jboss-kie-workbench/tests/bats/
      - run:
          name: Run jboss-kie-process-migration bats tests
          command: |
            $HOME/bin/bats jboss-kie-process-migration/tests/bats/
      - run:
          name: Run jboss-kie-dashbuilder bats tests
          command: |
            $HOME/bin/bats jboss-kie-dashbuilder/tests/bats/

      - run:
          name: Run os-eap-legacy/os-eap-launch tests
          command: |
            $HOME/bin/bats os-eap-legacy/os-eap-launch/tests/datasource.bats
      - run:
          name: Run os-eap-legacy/os-eap7-launch logging tests
          command: |
            $HOME/bin/bats os-eap-legacy/os-eap7-launch/tests/bats/logging/configure-logging-category.bats
      - run:
          name: Run os-eap-legacy/os-eap7-launch launch-common tests
          command: |
            $HOME/bin/bats os-eap-legacy/os-eap7-launch/tests/bats/launch-common/launch-common.bats
      - run:
          name: Run os-eap-legacy/os-eap7-launch datasources tests
          command: |
            $HOME/bin/bats os-eap-legacy/os-eap7-launch/tests/bats/datasource/configure.bats